"""
This is a data recipe based on live data modification from GUI
"""

from h2oaicore.data import CustomData


class DataRecipeNapubinu(CustomData):
    _display_name = "Data Recipe Napubinu"
    _description = "Generated by live code"

    @staticmethod
    def create_data(X):
        import datatable as dt
        X = dt.Frame(X)
        return X[:, [0,1,2,]]  # return dt.Frame, pd.DataFrame, np.ndarray or a list or named dict of those
